// Shader do núcleo raymarched (#ld-core no protótipo) — CoreSection.
// Portado literalmente: uma esfera recortada por planos octaédricos e
// cúbicos, oca, que se abre conforme o scroll (uOpen) e revela três anéis
// girando em torno de um núcleo pulsante, com refração na casca.

export function buildFragmentSrc(steps: number, innerSteps: number): string {
  return [
    "precision highp float;",
    "uniform vec2 uRes; uniform float uTime; uniform vec2 uMouse; uniform float uOpen; uniform float uRev;",
    "const vec3 BLUE = vec3(0.114,0.580,0.890);",
    "const vec3 WARM = vec3(0.843,0.643,0.353);",
    "mat3 rotY(float a){ float s=sin(a),c=cos(a); return mat3(c,0.,-s, 0.,1.,0., s,0.,c); }",
    "mat3 rotX(float a){ float s=sin(a),c=cos(a); return mat3(1.,0.,0., 0.,c,-s, 0.,s,c); }",
    "float sdTorus(vec3 p, vec2 t){ vec2 q = vec2(length(p.xz)-t.x, p.y); return length(q)-t.y; }",
    "float shellSDF(vec3 p){",
    "  vec3 q = p; q.y -= sign(p.y) * uOpen * 0.40;",
    "  float d = length(q) - 1.0;",
    "  vec3 c = rotY(uTime*0.17) * rotX(uTime*0.11) * q;",
    "  d = max(d, (abs(c.x)+abs(c.y)+abs(c.z))*0.5773 - 0.855);",
    "  d = max(d, max(abs(c.x), max(abs(c.y), abs(c.z))) - 0.795);",
    "  d = max(d, -(length(q) - 0.845));",
    "  return d;",
    "}",
    "float innerSDF(vec3 p){",
    "  vec3 r = rotY(uTime*0.52) * p;",
    "  float d = sdTorus(r, vec2(0.60, 0.014));",
    "  vec3 r2 = rotX(1.5708) * rotY(uTime*-0.38) * p;",
    "  d = min(d, sdTorus(r2, vec2(0.50, 0.012)));",
    "  vec3 r3 = rotX(0.9) * rotY(uTime*0.30) * p;",
    "  d = min(d, sdTorus(r3, vec2(0.38, 0.010)));",
    "  d = min(d, length(p) - (0.125 + 0.014*sin(uTime*2.1)));",
    "  return d;",
    "}",
    "vec3 shellNrm(vec3 p){ vec2 e = vec2(0.0018,0.0);",
    "  return normalize(vec3(shellSDF(p+e.xyy)-shellSDF(p-e.xyy), shellSDF(p+e.yxy)-shellSDF(p-e.yxy), shellSDF(p+e.yyx)-shellSDF(p-e.yyx))); }",
    "void main(){",
    "  vec2 uv = (gl_FragCoord.xy - 0.5*uRes) / min(uRes.x, uRes.y);",
    "  vec3 ro = vec3(0.0, 0.0, 3.15);",
    "  vec3 rd = normalize(vec3(uv, -1.45));",
    "  mat3 rot = rotY(uMouse.x*0.55 + uTime*0.05) * rotX(-uMouse.y*0.42);",
    "  ro = rot * ro; rd = rot * rd;",
    "  float t = 0.0, glow = 0.0; bool hit = false;",
    `  for (int i = 0; i < ${steps}; i++) {`,
    "    vec3 p = ro + rd*t;",
    "    float ds = shellSDF(p);",
    "    float di = innerSDF(p);",
    "    glow += (0.016 * uRev) / (1.0 + di*di*90.0);",
    "    float d = min(ds, di);",
    "    if (d < 0.0016) { hit = true; break; }",
    "    t += d * 0.78;",
    "    if (t > 8.0) break;",
    "  }",
    "  vec3 col = vec3(0.0); float a = 0.0;",
    "  if (hit) {",
    "    vec3 p = ro + rd*t;",
    "    if (innerSDF(p) < shellSDF(p)) {",
    "      float f = clamp(1.0 - (t - 2.0)/2.6, 0.15, 1.0);",
    "      col = (BLUE*1.25 + WARM*0.12) * f;",
    "      a = 1.0;",
    "    } else {",
    "      vec3 n = shellNrm(p);",
    "      float fres = pow(1.0 - max(dot(n, -rd), 0.0), 3.0);",
    "      vec3 L = normalize(vec3(0.55, 0.85, 0.45));",
    "      float dif = max(dot(n, L), 0.0);",
    "      float spec = pow(max(dot(reflect(-L, n), -rd), 0.0), 56.0);",
    "      float back = pow(max(dot(n, normalize(vec3(-0.75,-0.25,0.45))), 0.0), 5.0);",
    "      col = vec3(0.052)*(0.28 + 0.72*dif) + BLUE*fres*0.95 + vec3(1.0)*spec*0.32 + WARM*back*0.22;",
    "      float it = 0.02; vec3 rr = refract(rd, n, 0.86); if (length(rr) < 0.5) rr = rd;",
    `      for (int j = 0; j < ${innerSteps}; j++) {`,
    "        vec3 q = p + rr*it; float di = innerSDF(q);",
    "        if (di < 0.002) { col += (BLUE*0.95 + WARM*0.1) * (1.0 - fres) * 0.55; break; }",
    "        it += di * 0.9; if (it > 2.6) break;",
    "      }",
    "      a = 1.0;",
    "    }",
    "  }",
    "  col += BLUE * glow * 1.15; a = max(a, min(glow*1.6, 0.85));",
    "  float vig = smoothstep(1.25, 0.25, length(uv));",
    "  col *= 0.35 + 0.65*vig;",
    "  gl_FragColor = vec4(col * a, a);",
    "}",
  ].join("\n");
}

export const VERTEX_SRC = "attribute vec2 aP; void main(){ gl_Position = vec4(aP,0.0,1.0); }";
